import { NextRequest, NextResponse } from 'next/server';

/**
 * API endpoint to link a Telegram account using a 6-digit verification code
 * 
 * The verification code is generated by the Telegram bot and stored in Firestore.
 * This endpoint validates the code and links the Telegram user ID to the Firebase UID.
 */
export async function POST(request: NextRequest) {
    try {
        const { code } = await request.json();

        if (!code || typeof code !== 'string' || code.length !== 6) {
            return NextResponse.json(
                { error: '請提供有效的 6 位數驗證碼' },
                { status: 400 }
            );
        }

        // In a full implementation, this would:
        // 1. Get the current user's Firebase UID from the session
        // 2. Query Firestore for the verification code
        // 3. Validate it's not expired and not used
        // 4. Link the Telegram user ID to the Firebase UID
        // 5. Mark the code as used

        // For now, call the Cloud Function API
        const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://asia-east1-xxt-agent.cloudfunctions.net';
        
        const response = await fetch(`${apiBaseUrl}/linkTelegramAccount`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                // In production, include auth token
                // 'Authorization': `Bearer ${session.token}`,
            },
            body: JSON.stringify({ code }),
        });

        if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            return NextResponse.json(
                { error: errorData.error || '驗證碼無效或已過期' },
                { status: response.status }
            );
        }

        const data = await response.json();

        return NextResponse.json({
            success: true,
            message: 'Telegram 帳號綁定成功！',
            telegramUsername: data.telegramUsername,
        });

    } catch (error) {
        console.error('[API] Telegram link error:', error);
        return NextResponse.json(
            { error: '伺服器錯誤，請稍後再試' },
            { status: 500 }
        );
    }
}
