/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Content =
  | string
  | (
      | string
      | {
          [k: string]: unknown;
        }
    )[];
export type Type = string;
export type Name = string | null;
export type Id = string | null;
export type Messages = BaseMessage[];
export type CurrentStep = "analyze" | "plan" | "risk_check" | "execute" | "evaluate" | "complete" | "error";
export type Error = string | null;
export type Symbol = string;
export type Timeframe = string;
export type RiskLevel = "conservative" | "moderate" | "aggressive";
export type ExecutionMode = "advisory" | "paper_trade" | "live";
export type UserContext = string | null;
export type Symbol1 = string;
export type Price = number;
export type Open = number;
export type High = number;
export type Low = number;
export type Volume = number;
export type ChangePct1M = number;
export type VolatilityRegime = "low" | "normal" | "high";
export type Timestamp = string;
export type Severity = number;
export type Direction = "positive" | "negative";
export type DataQuality = "live" | "partial" | "mock";
export type Regime = "bull" | "bear" | "range" | "volatile" | "unknown";
export type Trend = "up" | "down" | "range";
export type Signals = {
  [k: string]: unknown;
}[];
export type Conviction = number;
export type Catalysts = string[];
export type Summary = string;
export type JudgmentBasis = string;
export type UncertaintyWarning = string;
export type IsCredible = boolean;
export type CredibilityScore = number;
export type SentimentDivergence = boolean;
export type DivergenceScore = number;
export type DivergenceDetail = string;
export type VerifiedCatalysts = string[];
export type FakeOrHypeWarnings = string[];
export type Summary1 = string;
export type JudgmentBasis1 = string;
export type CredibilityBasis = string;
export type PlanId = string;
export type Action = "BUY" | "SELL" | "HOLD" | "WATCH" | "HEDGE" | "REDUCE" | "AVOID";
export type Symbol2 = string;
export type AllocationPct = number;
export type EntryPrice = number | null;
export type StopLoss = number | null;
export type TakeProfit = number | null;
export type Timeframe1 = string;
export type Rationale = string;
export type BasisOfJudgment = string;
export type Actions = InvestmentAction[];
export type Confidence = number;
export type InvalidationRules = string[];
export type RiskFlags = string[];
export type Rationale1 = string;
export type AdvisoryDisclaimer = string;
export type BacktestEvidence = {
  [k: string]: unknown;
} | null;
export type Approved = boolean;
export type RiskScore = number;
export type Adjustments = {
  [k: string]: unknown;
}[];
export type Warnings = string[];
export type Violations = string[];
export type TradeId = string;
export type Symbol3 = string;
export type Action1 = string;
export type EntryPrice1 = number;
export type ExitPrice = number | null;
export type Pnl = number;
export type PnlPct = number;
export type Status = "open" | "closed" | "stopped_out" | "take_profit";
export type OpenedAt = string;
export type ClosedAt = string | null;
export type TradeResults = TradeResult[];
export type TotalValue = number;
export type Cash = number;
export type Positions = {
  [k: string]: unknown;
}[];
export type DailyPnl = number;
export type DailyPnlPct = number;
export type MaxDrawdown = number;
export type SharpeRatio = number | null;
export type WinRate = number | null;
export type TotalTrades = number;
export type SuccessfulPatterns = string[];
export type FailedPatterns = string[];
export type LastUpdated = string;
export type TrajectoryId = string | null;
export type SessionId = string;
export type StartedAt = string;
export type CompletedAt = string | null;
export type Iteration = number;
export type MaxIterations = number;

/**
 * The shared state flowing through the LangGraph investment supervisor.
 *
 * Each node reads what it needs and writes its output section.
 * The supervisor routes between nodes based on the current step.
 */
export interface InvestmentAgentState {
  messages?: Messages;
  current_step?: CurrentStep;
  error?: Error;
  symbol?: Symbol;
  timeframe?: Timeframe;
  risk_level?: RiskLevel;
  execution_mode?: ExecutionMode;
  user_context?: UserContext;
  price_snapshot?: PriceSnapshot | null;
  fusion_context?: FusionContext | null;
  market_insight?: MarketInsight | null;
  verification_insight?: VerificationInsight | null;
  investment_plan?: InvestmentPlan | null;
  risk_assessment?: RiskAssessment | null;
  trade_results?: TradeResults;
  portfolio?: PortfolioState | null;
  strategy_memory?: StrategyMemory | null;
  trajectory_id?: TrajectoryId;
  session_id?: SessionId;
  started_at?: StartedAt;
  completed_at?: CompletedAt;
  iteration?: Iteration;
  max_iterations?: MaxIterations;
  [k: string]: unknown;
}
/**
 * Base abstract message class.
 *
 * Messages are the inputs and outputs of a chat model.
 *
 * Examples include [`HumanMessage`][langchain.messages.HumanMessage],
 * [`AIMessage`][langchain.messages.AIMessage], and
 * [`SystemMessage`][langchain.messages.SystemMessage].
 */
export interface BaseMessage {
  content: Content;
  additional_kwargs?: AdditionalKwargs;
  response_metadata?: ResponseMetadata;
  type: Type;
  name?: Name;
  id?: Id;
  [k: string]: unknown;
}
export interface AdditionalKwargs {
  [k: string]: unknown;
}
export interface ResponseMetadata {
  [k: string]: unknown;
}
/**
 * Latest price data from market sources.
 */
export interface PriceSnapshot {
  symbol?: Symbol1;
  price?: Price;
  open?: Open;
  high?: High;
  low?: Low;
  volume?: Volume;
  change_pct_1m?: ChangePct1M;
  volatility_regime?: VolatilityRegime;
  timestamp?: Timestamp;
  [k: string]: unknown;
}
/**
 * Triple Fusion context from Event Fusion Engine.
 */
export interface FusionContext {
  market?: Market;
  news?: News;
  social?: Social;
  severity?: Severity;
  direction?: Direction;
  data_quality?: DataQuality;
  credibility_tiers?: CredibilityTiers;
  [k: string]: unknown;
}
export interface Market {
  [k: string]: unknown;
}
export interface News {
  [k: string]: unknown;
}
export interface Social {
  [k: string]: unknown;
}
export interface CredibilityTiers {
  [k: string]: unknown;
}
/**
 * Output of Market Analyst Agent.
 */
export interface MarketInsight {
  regime?: Regime;
  trend?: Trend;
  signals?: Signals;
  conviction?: Conviction;
  key_levels?: KeyLevels;
  catalysts?: Catalysts;
  summary?: Summary;
  judgment_basis?: JudgmentBasis;
  uncertainty_warning?: UncertaintyWarning;
  [k: string]: unknown;
}
export interface KeyLevels {
  [k: string]: unknown;
}
/**
 * Output of Information Verifier (Argus) Agent.
 */
export interface VerificationInsight {
  is_credible?: IsCredible;
  credibility_score?: CredibilityScore;
  sentiment_divergence?: SentimentDivergence;
  divergence_score?: DivergenceScore;
  divergence_detail?: DivergenceDetail;
  verified_catalysts?: VerifiedCatalysts;
  fake_or_hype_warnings?: FakeOrHypeWarnings;
  source_reliability?: SourceReliability;
  summary?: Summary1;
  judgment_basis?: JudgmentBasis1;
  credibility_basis?: CredibilityBasis;
  [k: string]: unknown;
}
export interface SourceReliability {
  [k: string]: unknown;
}
/**
 * Output of Strategy Planner Agent.
 */
export interface InvestmentPlan {
  plan_id?: PlanId;
  actions?: Actions;
  scenarios?: Scenarios;
  confidence?: Confidence;
  invalidation_rules?: InvalidationRules;
  risk_flags?: RiskFlags;
  rationale?: Rationale1;
  advisory_disclaimer?: AdvisoryDisclaimer;
  backtest_evidence?: BacktestEvidence;
  [k: string]: unknown;
}
/**
 * Single investment action in a plan.
 */
export interface InvestmentAction {
  action?: Action;
  symbol?: Symbol2;
  allocation_pct?: AllocationPct;
  entry_price?: EntryPrice;
  stop_loss?: StopLoss;
  take_profit?: TakeProfit;
  timeframe?: Timeframe1;
  rationale?: Rationale;
  basis_of_judgment?: BasisOfJudgment;
  [k: string]: unknown;
}
export interface Scenarios {
  [k: string]: unknown;
}
/**
 * Output of Risk Manager Agent.
 */
export interface RiskAssessment {
  approved?: Approved;
  risk_score?: RiskScore;
  adjustments?: Adjustments;
  warnings?: Warnings;
  violations?: Violations;
  adjusted_plan?: InvestmentPlan | null;
  [k: string]: unknown;
}
/**
 * Output of Execution Simulator Agent.
 */
export interface TradeResult {
  trade_id?: TradeId;
  symbol?: Symbol3;
  action?: Action1;
  entry_price?: EntryPrice1;
  exit_price?: ExitPrice;
  pnl?: Pnl;
  pnl_pct?: PnlPct;
  status?: Status;
  opened_at?: OpenedAt;
  closed_at?: ClosedAt;
  [k: string]: unknown;
}
/**
 * Current virtual portfolio state.
 */
export interface PortfolioState {
  total_value?: TotalValue;
  cash?: Cash;
  positions?: Positions;
  daily_pnl?: DailyPnl;
  daily_pnl_pct?: DailyPnlPct;
  max_drawdown?: MaxDrawdown;
  sharpe_ratio?: SharpeRatio;
  win_rate?: WinRate;
  total_trades?: TotalTrades;
  [k: string]: unknown;
}
/**
 * Past strategy performance for learning.
 */
export interface StrategyMemory {
  successful_patterns?: SuccessfulPatterns;
  failed_patterns?: FailedPatterns;
  regime_preferences?: RegimePreferences;
  last_updated?: LastUpdated;
  [k: string]: unknown;
}
export interface RegimePreferences {
  [k: string]: unknown;
}
